In [1]:
#Besher Hawoot 08/12/2022
#SIMPLE DECISION TREES

def simplDecisionTree(area, numberOfLevels):
    if (area <=  500) and (numberOfLevels <= 10):
        return "Tiny"
    elif (area <=  500) and (numberOfLevels > 10):
        return "Straw-Building"
    elif (area >  500) and (numberOfLevels > 10):
        return "Skyscraper"
    else:
        return "Mansion"
    
area = 900
numberOfLevels = 10
print("The house is",simplDecisionTree(area, numberOfLevels))

The house is Mansion


In [2]:
#Besher Hawoot 08/12/2022
#IMAGE EDITOR

import numpy as np

def photoEditor(image):
    for i in range(5):
        for j in range(5):
            image[i][4-j] = int(image[i][j]>=50)
    return image
            
image = [[10,20,30,40,50],[50,60,70,80,90],[90,80,70,60,50],[40,30,20,10,0],[55,45,65,35,75]]
image = np.array(image)
print(photoEditor(image))

[[0 0 0 0 0]
 [0 0 1 1 1]
 [0 0 1 1 1]
 [0 0 0 0 0]
 [0 0 1 0 1]]
